### ISSUE TITLE
重学CSS(一)：选择器

### ISSUE THREAD

**Issue by campcc** [campcc/blog#22]
> 全文约 2000 字，阅读完大约需要 5 分钟

`CSS` 中的模式匹配规则决定了哪些样式会被应用到 `CSSOM` 树中的元素，而这些模式就叫**选择器**。

选择器中，文档元素的大小写敏感性取决于文档语言，

比如 `HTML` 中，大小写是不敏感的，而在 `XML` 中，大小写是敏感的。

## 模式语法

下面是 [CSS2.1]() 规范中定义的选择器的模式，

### 通配选择器

`*`，匹配文档树中任意一个元素，

```css
* { font-family: sans-self; } // 这个字体的样式规则会对所有的文档元素生效
```

### 类型选择器

`element`，匹配文档元素的类型名

```css
h1 { margin: 0; } // 匹配文档树中的所有 h1 元素
```
### 后代选择器

`selector1 selector2`，匹配一个元素的后代元素

```css
h1 em { color: red; } // 匹配 h1 里面的所有 em 元素

div p *[herf] { padding: 0; } // 后代不一定必须是文档元素的类型名，比如这里，表示具有 href 属性集且位于本身位于 div 内部的 p 的内部的任意元素
```

### 子选择器

`selector1 > selector2`，匹配作为某些元素子级的元素

```css
body > p { line-height: 1.3; } // 匹配所有作为 body 子级的 p 元素
div ol>li p { line-height: 1.3; } // 匹配一个作为 li 元素后代的 p 元素，这个 li 元素必须是 ol 元素的子元素，且 ol 元素必须是 div 元素的后代
```

### 相邻兄弟选择器

`selector1 + selector2`，匹配拥有相同父级的元素

```css
math + p { text-indent: 0; }  // 当一个 p 元素紧跟在一个 math 元素后面时，它不应该缩进
```

### 属性选择器

`[attribute]`，属性选择器可以通过 4 种方式匹配。

- [attr]，匹配有指定属性名的元素，

```css
h1[title] { font-size: 18px; } // 匹配有 title 属性的 h1 元素
```

- [attr=val]，匹配属性值刚好是 `val` 的元素，

```css
span[class=example] { color: 'red'; } // 匹配 class 属性值为 example 的 span 元素
```

- [attr~=val]，匹配属性值刚好包含 `val` 的元素，

```css
a[rel~="copyright"] { color: 'gray'; } // 匹配 rel 属性值包含 copyright 的 a 元素
```

- [attr|=val]，匹配属性值以 `val` 开头的元素，

```css
*[lang|="en"] { color : red; } // 匹配 lang 属性值以 en 开头的元素
```

### 类选择器

**类选择器本质上就是属性选择器的一种**， 

它相当于 `[attr~=val]`，为了简化，我们使用句号 `.` 来表示类选择器，

```css
button.ant-btn { box-sizing: border-box; } // 匹配 class 为 ant-btn 的 button 元素
```

### ID选择器

无论在什么文档语言中，ID 属性都被用作元素的唯一标识，

```css
div#root { font-size: 1rem; } // 匹配 id 属性值为 root 的 div 元素
```

### 伪元素

伪元素的行为表现的像 `CSS` 中真实的元素一样，CSS2.1规范中共定义了 4 种伪元素

#### :first-line伪元素

`UA` 实现存在差异，一般用于对段落内容的第一个格式化行应用特殊样式，例如

```css
p:first-line { text-transform: uppercase; } // 每个段落的第一行的字母变成大写
```

#### :first-letter伪元素

最常见的用法是实现 **首字母下沉**，首字母必须出现在第一个格式化行，

```css
p:first-letter { text-transform: uppercase; }
```

#### :before伪元素

在一个元素的内容之后插入生成的内容

```css
h1:before {content: counter(chapno, upper-roman) ". "}
```

#### :after伪元素

在一个元素的内容之前插入生成的内容

```css
p.special:after {content: "Special! "}
```

### 伪类

伪类根据元素的特征分类，允许根据文档树之外的信息来格式化，常见的伪类有，

#### :first-child伪类

匹配一个作为某个其它元素的第一个子级的元素，比如，

```css
div > p:first-child { text-indent: 0; } // 匹配所有作为 div 元素的第一个子级的 p 元素，禁止 div 中的第一个段落缩进
```

需要注意的是，因为[匿名盒](http://www.ayqy.net/doc/css2-1/visuren.html#anonymous)不是文档树的一部分，计算第一个子级时不算它们，例如，

```html
<p>abc <em>default</em></p> // 这里 p 元素的第一个子级元素是 em
```

#### link伪类

为了匹配已访问和未访问的链接，`CSS` 提供了伪类 `:link` 和 `:visited` 作为区分，

```css
a.external:visited { color: blue; } // 匹配 class 为 external 的已访问链接
```

#### 动态伪类

交互式 `UA` 有时会改变渲染（效果）以响应用户动作，`CSS` 提供了 3 个伪类以实现这种交互效果，

`:hover`，`:active`，`:focus`，分别匹配悬停，激活和获取焦点的交互。

需要注意的是，`:hover` 必须放在 `link` 伪类（:link, :visited）后面，否则层叠规则将会隐藏 `:hover` 规则中的 `color` 属性，

```css
a:link    { color: red; }    /* unvisited links */
a:visited { color: blue; }   /* visited links   */
a:hover   { color: yellow; } /* user hovers     */
a:active  { color: lime; }   /* active links    */
```

#### 语言伪类

`HTML` 中，文档定义的语言是 `lang` 属性，伪类 `:lang(L)` 匹配语言为 `L` 的元素，大小写不敏感

下面的规则会给一个加拿大法语或德语 `HTML` 文档设置引号，

```css
html:lang(fr-ca) { quotes: '« ' ' »' }
html:lang(de) { quotes: '»' '«' '\2039' '\203A' }
:lang(fr) > Q { quotes: '« ' ' »' }
:lang(de) > Q { quotes: '»' '«' '\2039' '\203A' }
```

### CSS3新增的选择器

[CSS3新增选择器](https://www.cnblogs.com/libingql/p/4375354.html)

其中，关于伪类 `:nth-child(n)` 和 `:nth-of-type(n)` 的差异可以参考张鑫旭老师的[文章](https://www.zhangxinxu.com/wordpress/2011/06/css3%E9%80%89%E6%8B%A9%E5%99%A8nth-child%E5%92%8Cnth-of-type%E4%B9%8B%E9%97%B4%E7%9A%84%E5%B7%AE%E5%BC%82/)

## 优先级

优先级判定的算法为，

A specificity is determined by plugging numbers into (a, b, c, d):

1. If the styles are applied via the style attribute, a=1; otherwise, a=0.
2. b is equal to the number of ID selectors present.
3. c is equal to the number of class selectors, attribute selectors, and pseudoclasses present.
4. d is equal to the number of type selectors and pseudoelements present.

所以，**内联样式 > ID选择器 > 类选择器 > 类型选择器**

当然，规则都有例外，在一个样式声明中使用一个 `!important` 规则时，此声明将覆盖任何其他声明

## 写在最后

本文首发于我的 [博客](https://github.com/campcc/blog/issues/22)，才疏学浅，难免有错误，文章有误之处还望不吝指正！

如果有疑问或者发现错误，可以在评论区进行提问和勘误，

如果喜欢或者有所启发，欢迎 star，对作者也是一种鼓励。
